### ISSUE TITLE
Never resolving COMMAND_START_CODE_1 on response

### ISSUE THREAD

**Issue by LukeeeeBennett** [pkourany/FPS_GT511C3_Library#1]
I am experiencing an issue that is causing my photon to crash and thus need a factory flash.

I have highlighted the issue as line 718 of FPS_GT511C3.cpp where the firstbyte of the response packet within the GetResponse() method is not equal to Response_Packet::COMMAND_START_CODE_1 and never is, pushing the program into an infinite loop. On further inspection the FPS is continuously responding with 255 decimal. Maybe I can increase delay in that loop to avoid the crashing but either way the program will fail to proceed.

Do you know of a potential cause? Dead FPS?

**Comment by pkourany** [comment]
@LukeeeeBennett, sorry for the delay.  I only ported this library for a Community member and don't actually have a unit.  As such, I can't comment on the issue you are experiencing.

**Comment by LukeeeeBennett** [comment]
No worries @pkourany, I will resolve this problem when I have some more free time and will update with any findings here.

**Comment by jonathanGB** [comment]
@LukeeeeBennett have you solved your issue? If so, how did you solve it?

**Comment by guyk** [comment]
@LukeeeeBennett bump

**Comment by LukeeeeBennett** [comment]
@jonathanGB @guyk - Apologies for my lack of update. I haven't touched any hardware since this problem as I've been busy with software. I wish you the best.

**Comment by ScruffR** [comment]
I have no hardware to test this either (just as Paul), but looking at the issue description this seems to be the code part that needs altering
https://github.com/pkourany/FPS_GT511C3_Library/blob/master/FPS_GT511C3.cpp#715
```cpp
	while (done == false)
	{
		firstbyte = (byte)Serial1.read();
		if (firstbyte == Response_Packet::COMMAND_START_CODE_1)
		{
			done = true;
		}
	}
```
to something like this
```cpp
        uint32_t msTimeout = millis();
	while (!done && (millis() - msTimeout < WAIT4RESPONSE))  // #define WAIT4RESPONSE has to be set to an appropriat value
	{
		firstbyte = (byte)Serial1.read();
		if (firstbyte == Response_Packet::COMMAND_START_CODE_1)
		{
			done = true;
		}
                Particle.process();  // keep the device responsive to cloud activities like OTA flash
	}
        if (!done) return NULL; // the response pointer has to be checked for !NULL on the calling side
```
