### ISSUE TITLE
missing application.h

### ISSUE THREAD

**Issue by abluke** [pkourany/FPS_GT511C3_Library#2]
application.h is missing because of which execution of the program is not possible. Please figure out the issue as soon as possible.
Also requires application.cpp

**Comment by pkourany** [comment]
@abluke, `application.h` is included in FPS_GT511C3.h!  Are you using a Particle device?  You still need a user app such as one of the examples included examples directory.

**Comment by abluke** [comment]
@pkourany Okay, but i am using this in the arduino platform. Please help me to solve the issue.

**Comment by abluke** [comment]
Now I have a different set of errors. Please go through it.
Error is as follows:

Build options changed, rebuilding all
FPS_GT511C3_Library-master\FPS_GT511C3.cpp.o: In function `Command_Packet::GetPacketBytes()':
C:\Users\Dipti\Documents\Arduino\libraries\FPS_GT511C3_Library-master/FPS_GT511C3.cpp:18: undefined reference to `operator new[](unsigned int)'
FPS_GT511C3_Library-master\FPS_GT511C3.cpp.o: In function `FPS_GT511C3::GetResponse()':
C:\Users\Dipti\Documents\Arduino\libraries\FPS_GT511C3_Library-master/FPS_GT511C3.cpp:723: undefined reference to `operator new[](unsigned int)'
collect2.exe: error: ld returned 1 exit status
Error compiling.

The 'new' keyword seems to be a pretty basic one. Please let me know if you know the solution to this issue.

**Comment by pkourany** [comment]
@abluke, the original Arduinio library is here:

https://github.com/sparkfun/Fingerprint_Scanner-TTL
