### ISSUE TITLE
FPS_GT511C3.h does not work with ESP32 or ESP8266

### ISSUE THREAD

**Issue by philnicholson2005** [pkourany/FPS_GT511C3_Library#6]
Hi guys

im new to all this and im not sure that you are still working with this?

i would like to use this library with an ESP32 but ufortuantly it will not compile with any ESP board selected? if i create a new sketch with my board selected and add only one line #include "FPS_GT5113.h" it get the compiling error - any idea why the library or sketches will not work with an ESP board ??

thanks Phil

**Comment by pkourany** [comment]
@philnicholson2005, this library was adapted for the Particle Photon.

**Comment by philnicholson2005** [comment]
Thanks Paul,

Are you saying this library works with a Particle Photon as it stands?

Any reason why it doesn’t work with an ESP32?

Regards

Phil

________________________________

**Comment by pkourany** [comment]
@philnicholson2005, the hardware is different but you could adapt the library to use an ESP32 UART and change the low level serial functions accordingly.

**Comment by philnicholson2005** [comment]
Thanks Paul, I don’t know how to adapt or what to adapt so I may have to come up with another point of attack.......

But sorry if I am repeating myself, this library works with the particle photon? Or another library does?

Thanks

Phil

________________________________

**Comment by pkourany** [comment]
This library works with the Particle Photon, yes.
